### ISSUE TITLE
Logged warnings should be counted as failures, making the command return an error status code (1)

### ISSUE THREAD

**Issue by RonRademaker** [accompli/accompli#132]
It appears at least some failures, in this example related to composer install, do not cause accompli to halt and exit with a 'not ok' exit code. If used from automation (using for example `vendor/bin/accompli install-release master test && vendor/bin/accompli deploy-release master test`), the failed install will be installed resulting in a broken installation (I've had similar situations in other automated deployment setups). Example:

``` bash
                                    [ExecuteCommandTask       ] [!!!] Failed executing command "php bin/console cache:clear --env=prod".

=================
 Command output:
=================


  [Symfony\Component\Config\Exception\FileLoaderLoadException]
  The file "parameters.yml" does not exist (in: XXXXX/releases/master/app/config) in parameters.yml (which is being imported
   from "XXXX/releases/master/app/config/config.
  yml").



  [InvalidArgumentException]
  The file "parameters.yml" does not exist (in: XXXX/releases/master/app/config).
```

I tested this using:

``` bash
vendor/bin/accompli install-release master test -vvv && echo "DONE"
```

DONE was printed regardless of several errors occuring during install-release.

**Comment by niels-nijens** [comment]
Logged warnings aren't currently counted as failure. Probably some messages, currently logged as warnings, should actually be a higher log level and be counted as failure. 

As for the `ExecuteCommandTask` it should be possible configure if the task should be blocking or not.

**Comment by RonRademaker** [comment]
I don't think you should use logging for this, because logging is meant to inform the user about what happens (or make it possible to investigate what has happened), not to influence program execution flows.

Many tasks invoke external applications and the exits codes of those applications should be respected. This is something that can really threaten the stability of releases, I've seen (production) deployments broken because of checkout timeouts in composer, unavailable hosts for downloading packages and rebased released tags.
