### ISSUE TITLE
YAML config should run before ExecuteCommandTask (Symfony recipe)

### ISSUE THREAD

**Issue by RonRademaker** [accompli/accompli#133]
In the symfony cookbook example, the `Accompli\\Task\\YamlConfigurationTask` creates the parameter file. This task runs after composer install, causing composer install to fail due to a missing parameter.yml file. I can't find how /if I can change the order of the tasks to prevent this (and fix it with a documentation update).

**Comment by niels-nijens** [comment]
Thanks for reporting this. It's most likely caused by the priority of the `ComposerInstallTask`.

**Comment by niels-nijens** [comment]
Actually, the Composer installation can't fail due to a missing parameter.yml as it does not require it. The configured scripts will not run as the `ComposerInstallTask` uses the `--no-scripts` option during the `composer install`.

**Comment by RonRademaker** [comment]
> Actually, the Composer installation can't fail due to a missing parameter.yml as it does not require it. The configured scripts will not run as the ComposerInstallTask uses the --no-scripts option during the composer install.

You're right, the `YamlConfigurationTask` should run before the `ExecuteCommandTask`, not the `ComposerInstallTask` (see https://github.com/accompli/accompli/issues/132#issue-151159815 for the pasted error). The essence of the issue remains the same of course, the order of tasks matter.
