### ISSUE TITLE
Secret generation fails when releasing to multiple nodes

### ISSUE THREAD

**Issue by RonRademaker** [accompli/accompli#134]
The method to generate a secret in the parameter.yml file as described in the symfony cookbook fails when deploying to multiple nodes in the same stage. The secret defends against CSRF attacks, but is generated for each node, so if a form will be posted to a different node than the one that created the form, the application will break. This can be resolved by generating the secret once per running process.

**Comment by niels-nijens** [comment]
Generating a value with the `YamlConfigurationTask` will be removed (see #171). For now it's possible to configure your own 'secret' within the `accompli.json`.
