### ISSUE TITLE
Random "e" in command output.

### ISSUE THREAD

**Issue by deborahvandervegt** [accompli/accompli#182]
After the command output there is a random letter "e" visible.

![screenshot from 2016-06-28 10-14-12](https://cloud.githubusercontent.com/assets/13642829/16408459/2fb35f34-3d19-11e6-81b1-547a3c305fb2.png)

**Comment by deborahvandervegt** [comment]
The letter "e" is part of the outputted result. Narrowed it down to `src/Task/ComposerInstallTask.php` on Line 96. Printing $result->getOutput() gives: 

```
e
You are already using composer version 1.1.3 (stable channel).
```

**Comment by niels-nijens** [comment]
I haven't been able to reproduce this, but please re-open the issue when it occurs again.
