### ISSUE TITLE
Be more verbose when checkout was not done

### ISSUE THREAD

**Issue by gisostallenberg** [accompli/accompli#187]
As discussed.
An exception should be thrown when no checkout took place at [RemoteInstallStrategy.php#L61](https://github.com/accompli/accompli/blob/9451447811dd0c6a599780ded5ac0ea49501af35/src/Deployment/Strategy/RemoteInstallStrategy.php#L61)
Suggested exception

``` php
throw new Exception(sprintf('No task configured that checked out release version "%s".', $version) );
```

**Comment by niels-nijens** [comment]
Thanks.
