### ISSUE TITLE
Improve error of failed double install-release

### ISSUE THREAD

**Issue by gisostallenberg** [accompli/accompli#194]
When running `accompli install-release` for the same version you get the error:
`Failed to checkout version "#.#.#" from repository "git@github.com:My/Repo.git"`

I ran it twice because it failed for another reason before.
I think I should get a message saying: "Already installed" or the failure that happened before should not be intrusive on the second install.

Maybe I should also be allowed to run `accompli install-release --reinstall`, which forces a reinstall.

**Comment by niels-nijens** [comment]
This could be caused by the used git version. Which version of Accompli do you use and what does `-vvv` (v0.3.0) output?

**Comment by gisostallenberg** [comment]
It was with accompli 0.1.0, but also occurs with 0.3.0 `vendor/bin/accompli install-release -vvv 1.0.0 production`:

```
=================
 Command output:
=================

# github.com SSH-2.0-libssh-0.7.0

=================

                                    [RepositoryCheckoutTask   ] [...] Creating checkout of repository "git@github.com:My/Repo.git" for version "1.0.0".
                                                                Failed to checkout version "1.0.0" from repository "git@github.com:My/Repo.git".

=================
 Command output:
=================

* (no branch)

=================

```

**Comment by niels-nijens** [comment]
Ok. Some things to pinpoint the problem. Can you execute the following commands within the directory of the release (on the remote host) and post the output here?

```
git --version
git branch
echo $?
```

**Comment by gisostallenberg** [comment]
```
releases/1.0.0$ git --version
git version 1.7.10.4
releases/1.0.0$ git branch
* (no branch)
releases/1.0.0$ echo $?
0
```

**Comment by niels-nijens** [comment]
I've found the probable issue in Chrono. As `git branch` is not the problem it's probably failing during either `git fetch` or `git checkout`.

**Comment by gisostallenberg** [comment]
This issue is stale
