### ISSUE TITLE
FilePermissionTask only logs to user in verbose mode

### ISSUE THREAD

**Issue by reyostallenberg** [accompli/accompli#195]
The [FilePermissionTask](https://github.com/accompli/accompli/blob/master/src/Task/FilePermissionTask.php) only logs to user in verbose mode, while all other tasks notify the user that they are performing their task

**Comment by niels-nijens** [comment]
Thanks for reporting! We missed that one during the PR review.

The currently used `LogLevel::INFO` should be changed to `LogLevel::NOTICE`.
