### ISSUE TITLE
Conditional tasks

### ISSUE THREAD

**Issue by RonRademaker** [accompli/accompli#196]
I have an application that is deployed on multiple nodes. The application uses several background processes that consume message on from rabbitmq. I use the rabbitmq-supervisor-bundle to manage this. These processes need to be restarted when new code is deployed (perhaps even new processes are added or old ones are removed). I can use a task to accomplish that:

``` json
{
    "class": "Accompli\\Task\\ExecuteCommandTask",
    "events": ["accompli.install_release"],
    "command": "php bin/console rabbitmq-supervisor:rebuild"
},
```

However, these background processes should run on just one node, otherwise the same message would be consumed multiple times, resulting in for example double e-mails and pointless reindexing in an elastic search index. So, I'd like to be able to make a task conditional, in this case the condition would be the current host.

**Comment by niels-nijens** [comment]
Conditional tasks will be achieved by #35 and #36.
