### ISSUE TITLE
Use programmatically installation of composer

### ISSUE THREAD

**Issue by gisostallenberg** [accompli/accompli#197]
See https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md

**Comment by niels-nijens** [comment]
I'm not sure how Accompli would benefit from this. As this would still allow a man-in-the-middle attack.

**Comment by gisostallenberg** [comment]
I think it allows a man-in-two-middle's :wink: attack.

**Comment by niels-nijens** [comment]
In the case that the currently implemented method won't work any longer, I'll think about changing it to this method. 😉

**Comment by gisostallenberg** [comment]
This issue is stale
