### ISSUE TITLE
Allow custom stages

### ISSUE THREAD

**Issue by gisostallenberg** [accompli/accompli#198]
Currently only the stages _test,_ _acceptance_ and _production_ are allowed, see:
`hosts[*].stage : Does not match the regex pattern ^test|acceptance|production$"`

I think custom stages should be possible, for example _preview_, _playground_, _sandbox_...

**Comment by RonRademaker** [comment]
👍  on custom stages

**Comment by niels-nijens** [comment]
Most likely they're all derivatives of one of the development, test, acceptance or production stages. So, it might actually be better to go with tag-based filtering (#35). If you'd only want to deploy to a part of the hosts within a stage.

**Comment by RonRademaker** [comment]
I don't think this has to do with wanting to deploy to just as set of hosts, but really about getting a different environment. 

For example a training environment which will usually be production but with different parameters (i.e. databases), not necessarily on a different host (but it can be). But when there's a major release coming up, you might want to deploy your new acceptance environment so users can be trained for the changes to that particular environment. Tag based filtering would require you to always use a different host for the training environment and always run the same version as the production stage.

What is the benefit of limiting the allowed set of stages?

**Comment by gisostallenberg** [comment]
I think you should relate a stage to a type that is one of development|test|acceptance|production, as in preview|playground|sandbox|training: type=production

**Comment by niels-nijens** [comment]
> But when there's a major release coming up, you might want to deploy your new acceptance environment so users can be trained for the changes to that particular environment.

So, this would still be 'acceptance' with a different name to facilitate parameter changes.

> Tag based filtering would require you to always use a different host for the training environment and always run the same version as the production stage.

You're able to configure a host multiple times, but with different workspace paths.

> What is the benefit of limiting the allowed set of stages?

Ease of use, being able to differentiate on behavior in tasks based on stage and no typos.

**Comment by niels-nijens** [comment]
> I think you should relate a stage to a type that is one of development|test|acceptance|production, as in preview|playground|sandbox|training: type=production

Sort of creating an alias for one of the stages then? Or a host group identifier?

**Comment by gisostallenberg** [comment]
No, it should be a separate stage, but I think it has value to classify a stage as one of development|test|acceptance|production, because I think some tasks should run differently based on that classification.

**Comment by RonRademaker** [comment]
> Ease of use, being able to differentiate on behavior in tasks based on stage and no typos.

I guess I need to see the config, but it doesn't sound like an easy solution (from a users perspective). Anyway, if it's possible to deploy to the different situations it's 👍  by me.

**Comment by gisostallenberg** [comment]
> Anyway, if it's possible to deploy to the different situations it's :+1: by me.

:+1:

**Comment by niels-nijens** [comment]
@gisostallenberg what are suggesting in terms of host configuration? Something like this?

``` json
{
    "hostname": "example.com",
    "stage": "some-random-name",
    "environment": "production",
    "path": "/path/to/workspace"
}
```

**Comment by gisostallenberg** [comment]
This issue is stale
