### ISSUE TITLE
Add stage development

### ISSUE THREAD

**Issue by gisostallenberg** [accompli/accompli#199]
For a full DTAP environment it would be useful to have the _development_ stage, which is not allowed at the moment, see #198.

**Comment by niels-nijens** [comment]
How do think this would work? As you already need to have a clone of your project to get the `accompli.json`.

**Comment by gisostallenberg** [comment]
You could have a central server nightly distributing the latest development version to several development environments or just get the accompli.json for a run (accompli installed globally)

``` bash
mkdir /tmp/run-accompli/; cd /tmp/run-accompli/
wget https://raw.githubusercontent.com/account/project/master/accompli.json
...
```

**Comment by RonRademaker** [comment]
Why are the allowed stages limited to begin with? How would you use accompli for example if your project also requires environments like _training_ or _demo_?

**Comment by niels-nijens** [comment]
@RonRademaker That discussion is something that should take place in #198.

**Comment by gisostallenberg** [comment]
This issue is stale
