### ISSUE TITLE
Installation of branches possibility is not documented

### ISSUE THREAD

**Issue by gisostallenberg** [accompli/accompli#200]
At least in stage _development_ (not allowed at the moment, see #199) and _test_ it should be possible to install a branch instead of a release. Otherwise you have to create a release to test accompli itself.

**Comment by niels-nijens** [comment]
Installing a branch is already possible by supplying a branch name instead of a tag.

**Comment by niels-nijens** [comment]
I thought this was already documented, but couldn't find it.

**Comment by gisostallenberg** [comment]
This issue is stale
