### ISSUE TITLE
Stage specific configuration conflicts with shared releases

### ISSUE THREAD

**Issue by gisostallenberg** [accompli/accompli#203]
The [stage specific configuration](https://accompli.readme.io/v0.3/docs/yamlconfigurationtask#section-configuring-stage-specific-configuration) conflicts with the shared releases directory. 
When I run the commands below sequentially I might end up with a test database in production

``` bash
./vendor/bin/accompli install-release 1.0.0 production
./vendor/bin/accompli install-release 1.0.0 test
./vendor/bin/accompli deploy-release 1.0.0 production
```

**Comment by niels-nijens** [comment]
This is correct for Symfony deployments when you're using the same server and workspace path. When you're deploying two stages to the same server you should use separate workspace paths, at least for Symfony. This is something that is currently missing in de Symfony cookbook I think.

**Comment by gisostallenberg** [comment]
This issue is stale
