### ISSUE TITLE
Run composer without --no-dev in some stages

### ISSUE THREAD

**Issue by gisostallenberg** [accompli/accompli#204]
_development_ and _test_ stages require composer to install dev packages as well, as can be seen in https://github.com/symfony/symfony-standard/blob/69ddddab63d0bac1be152b6121e1dab0f7f30c83/app/AppKernel.php#L21
and 
https://github.com/sulu/sulu-standard/blob/4dcc2c6ff729a26c0a6cc00618e87339a2ef9cef/app/AbstractKernel.php#L84.

But in [ComposerInstallTask](https://github.com/accompli/accompli/blob/1732508334aac57f0fbf617bbc4684a573e6b348/src/Task/ComposerInstallTask.php#L122) --no-dev is used.

**Comment by niels-nijens** [comment]
I think you actually want to (manually) test how the test environment would run in production mode. You wouldn't be able to see if you accidently used require-dev packages in your production code.

Besides that, I was already thinking of making the various Composer configuration options configurable. Which makes this sort of related to #176.

**Comment by gisostallenberg** [comment]
This issue is stale
