### ISSUE TITLE
Restart a daemon during deployment

### ISSUE THREAD

**Issue by RonRademaker** [accompli/accompli#206]
I use accompli to deploy an application that uses supervisor to manage several rabbitmq consumer tasks (as I also explained in #196). The other issue I created deals with restarting the tasks when a new version is deployed, however I found this is not entirely correct. Because accompli always deploys a new version, I actually need to stop the supervisor running in the old version and than start a new one in the new to assure everything works correctly. 

I think this could be a more common use case, where you may need to perform some shutdown / uninstall task in the currently running version, before deploying the new version (so after `install` and before `deploy`).

**Comment by niels-nijens** [comment]
You can create your own task for this within your project. The task can handle stopping and starting the daemon on certain deployment events. See the documentation on [how to create your own task](https://github.com/accompli/accompli/blob/v0.3/docs/03-Tasks.md#creating-a-task).

**Comment by RonRademaker** [comment]
That task wil run in de document root of the new version if I understand correctly. What I'm talking about here is a task that should run in the document root of the _currently_ installed version.

**Comment by niels-nijens** [comment]
During deployment (the deploy-release command), both the new release and current release are available to be able to determine what a task should do.

See: [`DeployReleaseEvent`](https://github.com/accompli/accompli/blob/1732508334aac57f0fbf617bbc4684a573e6b348/src/EventDispatcher/Event/DeployReleaseEvent.php)

Also, when creating a custom task you're able to do whatever you want. You're not limited to any path or release. Although, it's advisable to make it sort of related to the release being installed / deployed. :smiley:

**Comment by RonRademaker** [comment]
Thanks, I created the task in https://github.com/ConnectHolland/Accompli-Daemon-Task.
