### ISSUE TITLE
The json schema is a bit too strict

### ISSUE THREAD

**Issue by RonRademaker** [accompli/accompli#208]
I was just testing a new Task and decided to use the local connection type to test the deployment on my local machine with this config:

```
{
    "stage": "test",
    "connectionType": "local",
    "path": "/Users/ron/Development/Tmp/MyProject"
},
```

Accompli failed due to:

```
[Accompli\Exception\JSONValidationException]
  The configuration file "/Users/ron/Development/src/MyProject/accompli.json" does not match the expected JSON schema.
```

After checking the schema I found the hostname is required, which seems a little pointless when releasing using the local connectionType.

**Comment by niels-nijens** [comment]
The hostname can be set to 'localhost'. The `LocalConnectionAdapter` will probably be the only connection adapter not requiring a hostname.

For the sake of consistency this won't be changed.
