### ISSUE TITLE
Create a task to update file permissions

### ISSUE THREAD

**Issue by niels-nijens** [accompli/accompli#46]
Create a task to update file permissions of configurable directories and files.

Related issue: #7

**Comment by niels-nijens** [comment]
Moving this issue to 0.2.0 because of the pending due date of 0.1.0.

**Comment by gisostallenberg** [comment]
Maybe allow acl when available

**Comment by deborahvandervegt** [comment]
I'm working on a PR for this issue. However at this point your desired solution is unclear to me...

On what level do you want the permissions to change? Possibilities are the release directory, the directory of the version it's installing, recursive, non-recursive...

Do you want to configure the directory in your accompli json? Do you want the possibility to configure the permissions per directory...?

**Comment by gisostallenberg** [comment]
IMO it should should be configurable which directories/files should be **writable** by the group the webserver (/apache) runs under. All other directories should not be writable.

**Comment by deborahvandervegt** [comment]
So you shouldn't be able to configure an entire set of permissions, like: 0770 for example? Just the directories?

**Comment by niels-nijens** [comment]
From a flexibility point of view it would be nice. Though, from a security point of view I'd rather not support making something world writable.

**Comment by niels-nijens** [comment]
Would something like this suffice?

``` json
{
    "class": "Accompli\\Task\\FilePermissionTask",
    "paths": {
        "a/path/within/release": {
            "recursive": true|false,
            "userRead": true|false,
            "userWrite": true|false,
            "userExecute": true|false,
            "groupRead": true|false,
            "groupWrite": true|false,
            "groupExecute": true|false
        }
    }
}
```

The different permissions represent an octal value which you can add and substract:

``` php
<?php
$value = 0000;
$value += 0400; // Add user read
$value += 0200; // Add user write
$value += 0100; // Add user execute

echo sprintf('%o', $value)."\n"; // Will output 0700 as string representation
```

Also see: http://permissions-calculator.org/

**Comment by gisostallenberg** [comment]
How about changing the group?

``` json
{
    "class": "Accompli\\Task\\FilePermissionTask",
    "paths": {
        "a/path/within/release": {
            "recursive": true|false,
            "permissions": "-rwxrwxr-x",
            "group": "www-data"
        }
    }
}
```

Trying to make something world writable should throw an exception

**Comment by niels-nijens** [comment]
Changing the group would require administrator rights through something sudo on Linux-based systems. sudo expects a password unless configured as NOPASSWD (which is insecure in my opinion).

Actually providing a password by Accompli is not really doable at the moment, but could be solved by something I'm working on with #177.

This task should focus on permissions for now, not ownership.

**Comment by gisostallenberg** [comment]
A user (owner) can change the group without needing any superuser rights, no password needed.
Only changing the owner is a superuser thing, because you could incriminate someone for instance. When acl is available even the required user can be **added**

**Comment by niels-nijens** [comment]
Ok. Guess I was doing something wrong with that then. :smiley:

Your proposal would create a more compact configuration.

Adding group ownership would probably make the name `Accompli\Task\FileOwnershipPermissionTask` more appropriate? Or just stay with the previous one?

**Comment by gisostallenberg** [comment]
FilePermissionTask is fine
