### ISSUE TITLE
Fix dependencies

### ISSUE THREAD

**Issue by gisoconnectholland** [accompli/accompli#51]
Some of the composer require items are full-filled by packages requirements which are in require-dev of accompli. The should be in the require-section of accompli:
- symfony/config
- symfony/yaml
- symfony/console
- psr/log

**Comment by niels-nijens** [comment]
Thanks! We don't have integration tests yet to prevent this kind of issue. I'll create a separate issue for that.

Can you provide a PR?

**Comment by gisoconnectholland** [comment]
symfony/console is already in require
I'll create a PR
