### ISSUE TITLE
Escape user input

### ISSUE THREAD

**Issue by gisostallenberg** [accompli/accompli#94]
I'm not sure if this is true in Accompli, but when \Symfony\Component\Process\Process is used possible user input should be escaped. 
This can be done using:

``` php
$process = \Symfony\Component\Process\ProcessBuilder::create()
   ->setPrefix('/my/bin')
   ->setArguments(array(
      sprintf('--hack="%s"', $userInput)
   ))
   ->getProcess();
```

User input can also reach the process via a database value and a cronjob in Garcon for example.
Please just close this issue when it is not applicable.

**Comment by RonRademaker** [comment]
If the incoming command in https://github.com/accompli/accompli/blob/807504727a5c29f0910f0cbd97fbead360e369b9/src/Deployment/Connection/LocalConnectionAdapter.php#L76 is not (always) escaped or filtered, this will be true.

**Comment by niels-nijens** [comment]
It's good to keep an eye on this. At this moment the only user input is through 2 command arguments version and stage.

Stage is validated to be one of test, acceptance or production.
Version isn't validated. At this point I can't really think of validation for it without restricting it.

The executeCommand method of a connection adapter is only reached through creating a task (or configuration).
I hope a developer wouldn't try to mess up his/her own project while deploying it.

**Comment by RonRademaker** [comment]
If version is escaped (the ProcessBuilder @gisostallenberg indicated uses ProcessUtils which uses escapeshellarg for this), there's no need to validate it (from a security point of view at least).

**Comment by niels-nijens** [comment]
I've investigated this further and it is currently not an issue. The version argument is escaped during a VCS checkout by Chrono. All other tasks currently check if it is a valid release (directory).

Though, I can imagine that developers creating custom tasks might make mistakes with this, so I'm going to add the posibility to add an array with arguments to `ConnectionAdapterInterface::executeCommand`. So, this is more a improve the ease of use for developers thing than a possible security issue at the moment.

**Comment by niels-nijens** [comment]
Moving this issue to 0.2.0 because of the pending due date of 0.1.0.
